name: Update CSV and Create PR

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-and-process-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set current date
        run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Update CSV
        run: npm run update-csv

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code ./data/utf_ken_all.csv && echo "changes=false" >> $GITHUB_OUTPUT || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Check for existing PR
        if: steps.git-check.outputs.changes == 'true'
        uses: actions/github-script@v6
        id: check-pr
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: 'update-zipcode-data-'
            });
            if (prs.data.length > 0) {
              console.log('Existing PR found. Exiting workflow.');
              core.setOutput('existing_pr', 'true');
            } else {
              console.log('No existing PR found. Proceeding with update.');
              core.setOutput('existing_pr', 'false');
            }

      - name: Parse CSV if changed
        if: steps.git-check.outputs.changes == 'true' && steps.check-pr.outputs.existing_pr != 'true'
        run: npm run parse-csv

      - name: Commit CSV changes
        if: steps.git-check.outputs.changes == 'true' && steps.check-pr.outputs.existing_pr != 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update zipcode data"

      - name: Update package.json patch version if changed
        if: steps.git-check.outputs.changes == 'true' && steps.check-pr.outputs.existing_pr != 'true'
        run: |
          npm version patch -m "Bump patch version to %s due to CSV update"
          echo "NEW_VERSION=$(npm pkg get version | tr -d '"')" >> $GITHUB_ENV

      - name: Create Pull Request if changed
        if: steps.git-check.outputs.changes == 'true' && steps.check-pr.outputs.existing_pr != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update CSV data and bump patch version
          title: Update CSV data to ${{ env.NEW_VERSION }} ${{ env.TODAY }}
          body: |
            This PR updates the CSV data and bumps the patch version.
            - Updated utf_ken_all.csv
            - Parsed new CSV data
            - Bumped patch version to ${{ env.NEW_VERSION }}
          branch: update-zipcode-data-${{ env.TODAY }}
          reviewers: |
            nickichi
          delete-branch: true